version: 2
updates:
  - package-ecosystem: gomod
    directory: ./
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      all-modules:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: ./
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      all-modules:
        patterns:
          - "*"
