broker:
  host: rabbitmq
  port: 5672
  user: test
  password: test
  vhost: sda
  exchange: sda
  ssl: False
database:
  host: postgres
  port: 5432
  user: postgres
  password: rootpasswd
  name: sda
  ssl_mode: disable
routing_key: inbox
s3inbox:
  endpoint: http://ceph-octopus:8100
  accessKey:
  secretKey:
  bucket: test
  region: us-east-1
  access_key: 
  secret_key: 
log:
  format: json
  level: debug
server:
  jwt_pub_key_path: /keys/
