storage:
  archive:
    s3:
    - endpoint: "http://s3:9000"
      access_key: "ElixirID"
      secret_key: "987654321"
      bucket_prefix: "archive"
      region: "us-east-1"
      disable_https: true

s3inbox:
  endpoint: "http://s3:9000"
  access_key: "ElixirID"
  secret_key: "987654321"
  bucket: "test"
  region: "us-east-1"
  ready_path: "/minio/health/ready"

c4gh:
  privateKeys:
  - filePath: /dev_utils/c4gh.sec.pem
    passphrase: "oaagCP1YgAZeEyl2eJAkHv9lkcWXWFgm"
