name: Go

on: [push]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.20"]
        os:
          - ubuntu-latest
          - windows-latest
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test -v -coverprofile=coverage -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage
          flags: unittests
          fail_ci_if_error: false
